services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    container_name: keycloak-idp
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_WEBAUTHN_RP_ID: ${KC_WEBAUTHN_RP_ID}
      KC_DEMO_ADDITIONAL_REDIRECT_URI: ${KC_DEMO_ADDITIONAL_REDIRECT_URI}
      KC_DEMO_ADDITIONAL_WEB_ORIGIN: ${KC_DEMO_ADDITIONAL_WEB_ORIGIN}
      KC_ALLOWED_BROWSER_ORIGIN: ${KC_ALLOWED_BROWSER_ORIGIN}
      KC_PASSKEY_CLIENT_ID: ${KC_PASSKEY_CLIENT_ID}
      KC_BROKER_CLIENT_ID: ${KC_BROKER_CLIENT_ID}
      KC_BROKER_CLIENT_SECRET: ${KC_BROKER_CLIENT_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/providers:/opt/keycloak/providers

  client:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && node index.js"
    environment:
      PORT: 3000
      BASE_PATH: ${BASE_PATH}
      PUBLIC_KEYCLOAK_URL: ${PUBLIC_KEYCLOAK_URL}
      PUBLIC_KEYCLOAK_ADMIN_URL: ${PUBLIC_KEYCLOAK_ADMIN_URL}
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./:/app
      - client_node_modules:/app/node_modules

volumes:
  keycloak_data:
  client_node_modules:
